### ISSUE TITLE
pip install pyjos 安装错误

### ISSUE THREAD

**Issue by tonywangcn** [tcztzy/pyjos#2]
Collecting pyjos
  Using cached pyjos-0.1.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-p0lwfrco/pyjos/setup.py", line 7, in <module>
        long_description=open('DESCRIPTION.rst').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'DESCRIPTION.rst'

**Comment by tcztzy** [comment]
Thank for your feedback, I will confirm this problem and fix it recently

**Comment by tcztzy** [comment]
Fix it, thank you for your feedback. Forgot to create a MANIFEST.in file to include DESCRIPTION.rst.

**Comment by tcztzy** [comment]
Since it is fixed, I close it.
